// 78 張塔羅牌資料（Rider-Waite-Smith，1909，公共領域）
// 每張牌附上正位／逆位的關鍵字與心理學角度的簡短解讀

const SUITS = {
  wands: { name: "權杖", element: "火", theme: "行動力、熱情與創造力" },
  cups: { name: "聖杯", element: "水", theme: "情感、關係與直覺" },
  swords: { name: "寶劍", element: "風", theme: "思維、溝通與真相" },
  pentacles: { name: "錢幣", element: "土", theme: "現實、資源與物質安全感" },
};

const RANK_LABELS = {
  1: "首牌", 2: "二", 3: "三", 4: "四", 5: "五", 6: "六", 7: "七",
  8: "八", 9: "九", 10: "十", 11: "侍者", 12: "騎士", 13: "皇后", 14: "國王",
};

const MAJOR_ARCANA = [
  { num: 0, name: "愚者", img: "00_fool.jpg",
    up: ["新的開始", "自由", "冒險", "信任未知"], rev: ["魯莽", "猶豫不決", "害怕改變"],
    upText: "全新的開始就在眼前，帶著對未知的信任輕盈上路，不被過去的包袱束縛。",
    revText: "可能因為過度衝動而忽略風險，或者被恐懼絆住，遲遲不敢跨出第一步。" },
  { num: 1, name: "魔術師", img: "01_magician.jpg",
    up: ["創造", "行動力", "資源整合", "意志集中"], rev: ["眼高手低", "自我懷疑", "能力被誤用"],
    upText: "你已具備將想法化為現實的資源與能力，此刻適合集中意志、主動創造。",
    revText: "空有想法卻遲遲不行動，或是把才華用錯了地方，也可能是被他人操弄。" },
  { num: 2, name: "女祭司", img: "02_high_priestess.jpg",
    up: ["直覺", "內在智慧", "沉靜", "尚未言明的知曉"], rev: ["忽視直覺", "壓抑感受", "資訊被隱藏"],
    upText: "答案往往不在外界的喧嘩裡，而在你安靜下來後浮現的直覺與內在知曉。",
    revText: "你可能正忽略內心的聲音，或是有些真相被刻意隱藏、尚未攤在陽光下。" },
  { num: 3, name: "皇后", img: "03_empress.jpg",
    up: ["豐盛", "滋養", "創造力", "感官享受"], rev: ["過度付出", "耗竭", "創造力受阻"],
    upText: "生命力正在流動，是滋養自己與他人、讓創造力自然開花的時刻。",
    revText: "長期的付出可能已讓你感到耗竭，是時候把滋養的能量留一些給自己。" },
  { num: 4, name: "皇帝", img: "04_emperor.jpg",
    up: ["秩序", "界線", "穩固結構", "理性掌控"], rev: ["過度控制", "僵化固執", "權威感低落"],
    upText: "透過建立清楚的界線與結構，你能為自己與他人帶來穩固可靠的秩序。",
    revText: "過於執著掌控可能讓關係變得僵硬，也可能反映出內在權威感的不足。" },
  { num: 5, name: "教皇", img: "05_hierophant.jpg",
    up: ["傳統智慧", "導師", "信念系統", "歸屬感"], rev: ["質疑教條", "打破框架", "尋找自己的信仰"],
    upText: "依循前人累積的智慧、尋求導師的引導，能帶來歸屬感與穩定的方向。",
    revText: "你正在質疑既有的規則與教條，想找到一套真正屬於自己的信念。" },
  { num: 6, name: "戀人", img: "06_lovers.jpg",
    up: ["深刻連結", "價值觀一致", "真誠抉擇"], rev: ["價值觀衝突", "關係失衡", "難以抉擇"],
    upText: "這是一個關於真誠連結與價值觀對齊的時刻，值得你認真面對內心的抉擇。",
    revText: "內在的價值觀正在拉扯，或關係中出現失衡，讓抉擇變得格外困難。" },
  { num: 7, name: "戰車", img: "07_chariot.jpg",
    up: ["意志力", "整合衝突", "勇往直前"], rev: ["方向失控", "內在拉扯", "停滯不前"],
    upText: "憑藉堅定的意志力整合內在相互矛盾的力量，能一路勇往直前朝目標邁進。",
    revText: "內在的拉扯讓方向感變得模糊，行動力也因此卡住、難以推進。" },
  { num: 8, name: "力量", img: "08_strength.jpg",
    up: ["溫柔的韌性", "馴服恐懼", "耐心"], rev: ["自我懷疑", "被衝動主導", "缺乏耐心"],
    upText: "真正的力量不是蠻力，而是用溫柔與耐心去馴服內心的恐懼與衝動。",
    revText: "此刻可能被恐懼或一時的衝動牽著走，對自己少了一份耐心與信任。" },
  { num: 9, name: "隱者", img: "09_hermit.jpg",
    up: ["向內探尋", "獨處沉澱", "內在的光"], rev: ["過度孤立", "逃避人群", "迷惘"],
    upText: "適合暫時退到人群之外，向內探尋，找到屬於自己的那盞內在的光。",
    revText: "獨處可能已經變成逃避，或是在孤立中反而更加迷失了方向。" },
  { num: 10, name: "命運之輪", img: "10_wheel_of_fortune.jpg",
    up: ["轉折", "接受變化", "把握機運"], rev: ["抗拒改變", "被命運擺佈", "時運不濟"],
    upText: "生命的節奏正在轉動，願意順勢而為、把握機運，就能乘著變化向前。",
    revText: "你可能正在抗拒眼前的變化，或感覺諸事不順、被局勢牽著走。" },
  { num: 11, name: "正義", img: "11_justice.jpg",
    up: ["誠實面對因果", "公平", "道德平衡"], rev: ["逃避責任", "失衡的判斷", "感覺不公"],
    upText: "誠實面對事情的因果，用公平清楚的態度為自己的選擇負責。",
    revText: "可能正在逃避該負的責任，或者判斷失了準頭，也可能覺得受到不公對待。" },
  { num: 12, name: "倒吊人", img: "12_hanged_man.jpg",
    up: ["換個角度", "主動的暫停", "臣服帶來領悟"], rev: ["無謂的犧牲", "停滯", "找不到意義"],
    upText: "主動停下腳步、換個角度看世界，臣服於當下反而能帶來新的領悟。",
    revText: "犧牲和等待似乎沒有帶來意義，只是卡在原地，找不到出路。" },
  { num: 13, name: "死神", img: "13_death.jpg",
    up: ["徹底的結束", "重生", "放下不再適合的階段"], rev: ["抗拒結束", "卡在過去", "不願放手"],
    upText: "某個階段正走向徹底的結束，唯有放下，才能為重生騰出空間。",
    revText: "你可能還緊抓著已經不再適合的人事物，遲遲不願意放手告別。" },
  { num: 14, name: "節制", img: "14_temperance.jpg",
    up: ["調和", "耐心融合", "中庸之道"], rev: ["失衡", "過猶不及", "內外不協調"],
    upText: "耐心地調和身心與對立的兩端，慢慢找到屬於自己的中庸之道。",
    revText: "生活的某些部分正明顯失衡，內在與外在之間也有些不協調。" },
  { num: 15, name: "惡魔", img: "15_devil.jpg",
    up: ["成癮與慾望", "自我限制", "看清束縛"], rev: ["開始掙脫", "覺察限制性信念", "鬆綁"],
    upText: "面對慾望、成癮或自我設限的模式，第一步是誠實地看清束縛從何而來。",
    revText: "你正開始覺察並鬆綁那些長期困住自己的限制性信念，掙脫的力量已在萌芽。" },
  { num: 16, name: "塔", img: "16_tower.jpg",
    up: ["突如其來的瓦解", "震盪", "必要的覺醒"], rev: ["逃避崩解", "壓抑終將爆發", "延遲的危機"],
    upText: "舊有的結構突然瓦解，雖然震盪痛苦，卻帶來了必要且深刻的覺醒。",
    revText: "危機或許被暫時壓抑下來，但逃避崩解只會讓爆發延遲、代價更大。" },
  { num: 17, name: "星星", img: "17_star.jpg",
    up: ["風暴過後的希望", "療癒", "重新相信"], rev: ["信心動搖", "希望渺茫", "與內在失聯"],
    upText: "風暴過去之後，療癒與希望正在悄悄回來，值得重新相信自己與未來。",
    revText: "此刻信心有些動搖，感覺希望渺茫，也可能與內在的力量暫時失去連結。" },
  { num: 18, name: "月亮", img: "18_moon.jpg",
    up: ["潛意識浮現", "夢境", "直面內心的恐懼"], rev: ["迷霧漸散", "真相逐漸清晰"],
    upText: "潛意識與模糊的不安正在浮現，這是直面內心恐懼與幻象的時刻。",
    revText: "原本混淆不清的迷霧正在逐漸散去，真相開始變得清晰可辨。" },
  { num: 19, name: "太陽", img: "19_sun.jpg",
    up: ["清晰的喜悅", "真實自我", "活力"], rev: ["暫時的低潮", "過度樂觀掩蓋真實感受"],
    upText: "清晰而純粹的喜悅正在展現，這是活出真實自我、充滿活力的時刻。",
    revText: "可能正經歷一段暫時的低潮，或是用過度樂觀掩蓋了真實的感受。" },
  { num: 20, name: "審判", img: "20_judgement.jpg",
    up: ["重新評估", "覺醒", "自我寬恕"], rev: ["過度自我批判", "逃避內在的呼喚"],
    upText: "是時候重新評估過去的自己，在覺醒中學習自我寬恕、回應內在的召喚。",
    revText: "對自己過於嚴苛的批判，可能讓你逃避了那個真正需要面對的呼喚。" },
  { num: 21, name: "世界", img: "21_world.jpg",
    up: ["完整", "整合", "一個循環的圓滿完成"], rev: ["尚未完成", "缺乏收尾感", "懸而未決"],
    upText: "一個重要的循環正走向完整與整合，值得為這份圓滿好好慶祝。",
    revText: "某個課題似乎還沒有真正完成，缺少一個讓自己安心收尾的句點。" },
];

const MINOR_ARCANA = {
  wands: [
    { rank: 1, upText: "新的靈感與行動的衝動湧現，是充滿創造能量的起點。", revText: "靈感受到阻塞，遲遲無法把想法真正展開成行動。",
      up: ["靈感", "起點", "創造衝動"], rev: ["靈感受阻", "遲滯"] },
    { rank: 2, upText: "站在十字路口規劃長遠的藍圖，冷靜評估下一步的可能性。", revText: "面對選擇感到猶豫，害怕跨出熟悉的舒適圈。",
      up: ["規劃", "遠見", "評估"], rev: ["猶豫", "畏懼改變"] },
    { rank: 3, upText: "初步的努力開始看見成果，可以放眼更遠的未來布局。", revText: "計畫的進度比預期延遲，需要多一點耐心等待成果。",
      up: ["拓展", "初見成果", "遠見"], rev: ["延遲", "缺乏耐心"] },
    { rank: 4, upText: "值得慶祝的階段性成果，帶來穩固的歸屬感與喜悅。", revText: "內部出現一些不合，原本該慶祝的時刻被往後延遲。",
      up: ["慶祝", "歸屬感", "穩固"], rev: ["不合", "延遲的喜悅"] },
    { rank: 5, upText: "意見紛雜引發的競爭與摩擦，其實也在激盪出成長。", revText: "選擇逃避衝突或陷入內耗，紛爭遲遲沒有解決。",
      up: ["競爭", "摩擦", "成長"], rev: ["逃避衝突", "內耗"] },
    { rank: 6, upText: "努力獲得眾人的認可，帶著自信邁向屬於自己的勝利。", revText: "缺乏被肯定的感覺，太過在意他人眼光而不敢往前。",
      up: ["認可", "自信", "勝利"], rev: ["缺乏肯定", "在意他人眼光"] },
    { rank: 7, upText: "在壓力之下依然堅守自己的立場與信念，勇敢地捍衛。", revText: "疲於招架四面而來的挑戰，開始懷疑堅持是否還值得。",
      up: ["堅守立場", "捍衛信念"], rev: ["疲於應付", "動搖"] },
    { rank: 8, upText: "事情正快速推進，訊息與行動一波接著一波湧現。", revText: "進度出現延宕，溝通之間開始出現落差與混亂。",
      up: ["快速推進", "行動力"], rev: ["延宕", "溝通混亂"] },
    { rank: 9, upText: "帶著過往的傷痕仍然堅韌防守，在接近終點前保持警覺。", revText: "過度防備讓身心俱疲，卻始終不敢真正放鬆下來。",
      up: ["堅韌", "警覺", "接近終點"], rev: ["過度防備", "疲憊"] },
    { rank: 10, upText: "扛起了過多的責任，被沉重的負擔壓得有些喘不過氣。", revText: "開始學習把責任適度分攤出去，不必獨自扛下一切。",
      up: ["重擔", "責任過多"], rev: ["學習放下", "分攤"] },
    { rank: 11, upText: "帶著初學者的好奇與熱情，對新的想法躍躍欲試。", revText: "三分鐘熱度，計畫還停留在空想、尚未真正落實。",
      up: ["好奇", "初學熱情"], rev: ["三分鐘熱度", "空想"] },
    { rank: 12, upText: "衝勁十足、勇於冒險，行動力旺盛卻也可能操之過急。", revText: "行事魯莽躁進，或是熱情來得快也去得快、半途而廢。",
      up: ["衝勁", "勇於冒險"], rev: ["魯莽", "半途而廢"] },
    { rank: 13, upText: "自信、溫暖且極具感染力，是能帶動他人前進的行動者。", revText: "內在缺乏安全感，展現出來的可能是過度強勢或自我懷疑。",
      up: ["自信", "感染力", "領導"], rev: ["缺乏安全感", "強勢"] },
    { rank: 14, upText: "以清楚的願景與魄力領導，成熟地掌握自己的熱情。", revText: "行事專斷獨行，或是長期壓抑了自己內在的創造衝動。",
      up: ["願景", "魄力", "成熟領導"], rev: ["專斷", "壓抑創造力"] },
  ],
  cups: [
    { rank: 1, upText: "情感或關係迎來全新的開端，心中湧現愛與感動。", revText: "情感有些封閉，內心真實的感受被自己壓抑了下來。",
      up: ["新的情感", "感動", "敞開心"], rev: ["情感封閉", "壓抑感受"] },
    { rank: 2, upText: "兩人之間有著真誠的情感連結，彼此理解、互相靠近。", revText: "關係中出現失衡，誤解或距離讓兩人漸行漸遠。",
      up: ["真誠連結", "相互理解"], rev: ["失衡", "誤解"] },
    { rank: 3, upText: "與朋友或群體一起共享喜悅，值得好好慶祝這份情誼。", revText: "在群體中感到疏離，或是過度沉溺社交而忽略了自己。",
      up: ["共享喜悅", "情誼"], rev: ["疏離", "忽略自己"] },
    { rank: 4, upText: "對眼前的現況感到有些麻木，可能忽略了身邊出現的機會。", revText: "重新對生活產生興趣，願意再次敞開心接受新的可能。",
      up: ["麻木", "忽略機會"], rev: ["重燃興趣", "敞開心"] },
    { rank: 5, upText: "沉浸在失落與遺憾裡，還沒看見身邊其實仍有支持存在。", revText: "開始慢慢從悲傷中走出來，學著接受並釋懷過去。",
      up: ["失落", "遺憾"], rev: ["釋懷", "走出悲傷"] },
    { rank: 6, upText: "懷念起純真的過去，從舊時光的回憶裡獲得溫暖的力量。", revText: "過度依戀過去，反而讓自己逃避了面對當下的現實。",
      up: ["懷舊", "純真的溫暖"], rev: ["過度依戀過去", "逃避現實"] },
    { rank: 7, upText: "眼前充滿誘人的選項，卻也容易讓人迷失在幻想之中。", revText: "開始看清幻象背後的真相，能做出更務實清晰的選擇。",
      up: ["幻想", "眾多選項"], rev: ["看清真相", "務實抉擇"] },
    { rank: 8, upText: "為了追尋更深的意義，主動離開一個看似完美的現況。", revText: "猶豫著是否該放手離開，害怕面對未知的旅程。",
      up: ["追尋意義", "主動離開"], rev: ["猶豫離開", "害怕未知"] },
    { rank: 9, upText: "情感與物質層面都感到滿足，是願望實現後的喜悅時刻。", revText: "表面看似滿足，內心卻空虛，可能過度追求感官上的享受。",
      up: ["滿足", "願望實現"], rev: ["表面滿足", "內心空虛"] },
    { rank: 10, upText: "情感圓滿，家庭與關係之中有著深刻而長久的和諧幸福。", revText: "表面和樂融融，卻藏著尚未被說開的家庭或關係裂痕。",
      up: ["圓滿", "和諧幸福"], rev: ["表面和樂", "未解的裂痕"] },
    { rank: 11, upText: "以赤子之心敞開感受，對情感的世界充滿好奇與想像。", revText: "情緒化或不太成熟地在表達自己的情感需求。",
      up: ["赤子之心", "好奇想像"], rev: ["情緒化", "不成熟表達"] },
    { rank: 12, upText: "浪漫而理想化，順著情感的呼喚勇敢地採取行動。", revText: "情緒起伏不定，用美好的幻想取代了真實的行動。",
      up: ["浪漫", "順心而行"], rev: ["情緒不定", "以幻想代替行動"] },
    { rank: 13, upText: "深具同理心，能溫柔地涵容自己與他人的情感。", revText: "過度共情讓情緒界線變得模糊，容易被他人的感受淹沒。",
      up: ["同理心", "情感涵容力"], rev: ["界線模糊", "過度共情"] },
    { rank: 14, upText: "情感成熟穩定，能夠理性同時又溫柔地處理內心的感受。", revText: "習慣壓抑情緒，或用冷漠來掩飾內心真實的波動。",
      up: ["成熟穩定", "理性又溫柔"], rev: ["壓抑情緒", "冷漠掩飾"] },
  ],
  swords: [
    { rank: 1, upText: "思路豁然開朗，是一個能夠看清真相的清晰時刻。", revText: "思緒混亂，被扭曲的資訊或彼此的誤解困住。",
      up: ["清晰", "看清真相"], rev: ["思緒混亂", "誤解"] },
    { rank: 2, upText: "在兩難之間刻意迴避抉擇，內心正處於一種僵持的狀態。", revText: "長期逃避之後，終於必須正視眼前那個抉擇。",
      up: ["迴避抉擇", "僵持"], rev: ["正視抉擇", "無法再逃"] },
    { rank: 3, upText: "心碎與失望帶來的雖然痛苦，卻也換來清晰的領悟。", revText: "傷痛正逐漸癒合，開始學習原諒他人也原諒自己。",
      up: ["心碎", "痛苦的清晰"], rev: ["癒合", "學習原諒"] },
    { rank: 4, upText: "主動讓自己休息、沉澱，讓心智從紛擾中好好恢復。", revText: "被迫停下腳步休養，或休息過後正重新恢復行動力。",
      up: ["主動休息", "沉澱"], rev: ["被迫停下", "恢復中"] },
    { rank: 5, upText: "贏了眼前的爭辯，卻可能因此失去了關係，值得反思代價。", revText: "願意放下對錯的爭執，主動尋求和解的可能。",
      up: ["贏了爭辯", "代價"], rev: ["放下爭執", "尋求和解"] },
    { rank: 6, upText: "帶著身上的傷痛，緩緩地過渡到一個更平靜的境地。", revText: "遲遲無法真正離開困境，停滯在過渡的路途中間。",
      up: ["緩緩過渡", "邁向平靜"], rev: ["停滯", "無法離開"] },
    { rank: 7, upText: "靠著策略或迴避的手段獨自解決問題，但需留意誠信。", revText: "隱瞞的事情終究被揭穿，或是決定坦誠面對真相。",
      up: ["策略", "獨自應對"], rev: ["隱瞞被揭穿", "選擇坦誠"] },
    { rank: 8, upText: "被自己的思維困住了手腳，其實選擇比想像中還要多。", revText: "開始鬆綁那些限制性的信念，重新找回自己的主控權。",
      up: ["自我設限", "困住的思維"], rev: ["鬆綁信念", "找回主控權"] },
    { rank: 9, upText: "深夜裡的焦慮與反覆思考，擔憂被想像放得無限大。", revText: "焦慮的情緒逐漸緩和，開始能更理性地看待擔心的事。",
      up: ["焦慮", "反芻思考"], rev: ["焦慮緩解", "理性看待"] },
    { rank: 10, upText: "徹底的結束帶來痛苦的谷底，但這也正是重生的起點。", revText: "正從谷底緩慢復原，最難熬的階段即將要過去了。",
      up: ["谷底", "痛苦的終結"], rev: ["緩慢復原", "即將過去"] },
    { rank: 11, upText: "求知若渴，帶著警覺又好奇的心觀察著周遭的一切。", revText: "言語有些衝動，或無意間散播了未經查證的訊息。",
      up: ["求知若渴", "警覺觀察"], rev: ["言語衝動", "未經查證"] },
    { rank: 12, upText: "果斷而直接，迅速地採取行動去追求心中認定的真相。", revText: "說話衝動容易傷人，行事也顯得魯莽、少了考量。",
      up: ["果斷", "追求真相"], rev: ["衝動傷人", "魯莽"] },
    { rank: 13, upText: "理性而獨立，能用清晰的洞察力看穿事物的表象。", revText: "言辭可能過於尖銳，或用理智過度武裝了自己的脆弱。",
      up: ["理性獨立", "洞察力"], rev: ["言辭尖銳", "武裝脆弱"] },
    { rank: 14, upText: "以邏輯與公正的判斷力，做出理性而周全的決策。", revText: "可能過度批判他人，或濫用自身的權威去壓制對方。",
      up: ["理性判斷", "公正"], rev: ["過度批判", "濫用權威"] },
  ],
  pentacles: [
    { rank: 1, upText: "一個實際機會正在萌芽，是扎根於現實的全新開始。", revText: "錯失了眼前的機會，或是基礎不穩導致計畫落空。",
      up: ["機會萌芽", "扎根現實"], rev: ["錯失機會", "基礎不穩"] },
    { rank: 2, upText: "靈活地調度手上的資源與時間，在變動之中找到平衡。", revText: "分身乏術，資源與時間的調度出現了失衡。",
      up: ["靈活調度", "動態平衡"], rev: ["分身乏術", "調度失衡"] },
    { rank: 3, upText: "透過合作與各自的專業，齊心完成一項扎實的成果。", revText: "團隊之間缺乏共識，各自為政影響了整體的進度。",
      up: ["合作", "專業", "扎實成果"], rev: ["缺乏共識", "各自為政"] },
    { rank: 4, upText: "緊緊抓住手中的資源與安全感，對改變感到有些抗拒。", revText: "開始學習鬆手，對物質與安全感的執著漸漸放下。",
      up: ["抓緊資源", "抗拒改變"], rev: ["學習放手", "鬆開執著"] },
    { rank: 5, upText: "面對匱乏與孤立的處境，卻忽略了身邊其實仍有的支持。", revText: "正在走出困境，重新找到能依靠的資源與歸屬感。",
      up: ["匱乏", "孤立"], rev: ["走出困境", "重獲支持"] },
    { rank: 6, upText: "在給予與接受之間找到平衡，慷慨地與他人分享資源。", revText: "資源的分配並不對等，施與受的關係出現失衡。",
      up: ["給予與接受", "慷慨分享"], rev: ["分配不均", "失衡"] },
    { rank: 7, upText: "停下腳步檢視至今的付出，評估是否值得繼續投入下去。", revText: "對緩慢的進展感到沮喪，缺乏繼續等待的耐心。",
      up: ["檢視付出", "評估投入"], rev: ["缺乏耐心", "沮喪"] },
    { rank: 8, upText: "專注地磨練手上的技藝，透過踏實累積邁向精通。", revText: "對眼前的工作有些敷衍了事，或是漸漸失去了熱忱。",
      up: ["專注磨練", "踏實累積"], rev: ["敷衍", "失去熱忱"] },
    { rank: 9, upText: "憑藉自己的努力獲得獨立自主，享受這份富足的成果。", revText: "過度追求物質上的成就，卻忽略了對自己的照顧。",
      up: ["獨立自主", "富足"], rev: ["過度追求物質", "忽略自我照顧"] },
    { rank: 10, upText: "長遠累積下來的富足，來自家族與傳承所帶來的安穩。", revText: "家族的財務或價值觀之間，出現了分歧與不穩定。",
      up: ["長遠富足", "傳承與安穩"], rev: ["價值觀分歧", "不穩定"] },
    { rank: 11, upText: "對學習新技能與看得見的成果，帶著踏實的好奇心。", revText: "缺乏執行上的紀律，計畫容易流於空談。",
      up: ["踏實好奇", "學習新技能"], rev: ["缺乏紀律", "流於空談"] },
    { rank: 12, upText: "穩健而踏實，願意按部就班地朝目標一步步前進。", revText: "行事過於保守僵化，或行動力顯得停滯不前。",
      up: ["穩健踏實", "按部就班"], rev: ["保守僵化", "停滯不前"] },
    { rank: 13, upText: "務實而溫暖，善於在現實生活中創造出滋養人心的空間。", revText: "長期過度操勞，忽略了自己內在真正的需求。",
      up: ["務實溫暖", "創造滋養空間"], rev: ["過度操勞", "忽略自我需求"] },
    { rank: 14, upText: "擁有穩健的實務能力，是長期累積而成的豐盛成果。", revText: "過度重視物質上的成就，忽略了內在真正的價值。",
      up: ["穩健實務", "豐盛成果"], rev: ["重物質輕內在", "失衡的價值觀"] },
  ],
};

// 每張牌的核心主題標籤，用於「AI 心理分析」比對牌與牌之間的共鳴／張力，
// 而不只是逐張解讀。標籤共 12 種：
// begin 起點　end 結束放下　conflict 衝突對抗　clarity 清晰真相
// confusion 混亂焦慮　connection 連結關係　isolation 孤立獨處
// resource 資源現實　instability 失衡不穩定　growth 累積成長
// power 掌控行動力　surrender 臣服療癒
const CARD_THEMES = {
  "major-0": "begin", "major-1": "power", "major-2": "clarity", "major-3": "resource",
  "major-4": "power", "major-5": "connection", "major-6": "connection", "major-7": "power",
  "major-8": "surrender", "major-9": "isolation", "major-10": "instability", "major-11": "clarity",
  "major-12": "surrender", "major-13": "end", "major-14": "surrender", "major-15": "confusion",
  "major-16": "conflict", "major-17": "surrender", "major-18": "confusion", "major-19": "clarity",
  "major-20": "clarity", "major-21": "end",
  "wands-1": "begin", "wands-2": "growth", "wands-3": "growth", "wands-4": "connection",
  "wands-5": "conflict", "wands-6": "power", "wands-7": "conflict", "wands-8": "growth",
  "wands-9": "conflict", "wands-10": "instability", "wands-11": "begin", "wands-12": "power",
  "wands-13": "power", "wands-14": "power",
  "cups-1": "begin", "cups-2": "connection", "cups-3": "connection", "cups-4": "confusion",
  "cups-5": "end", "cups-6": "connection", "cups-7": "confusion", "cups-8": "end",
  "cups-9": "resource", "cups-10": "connection", "cups-11": "begin", "cups-12": "connection",
  "cups-13": "connection", "cups-14": "connection",
  "swords-1": "clarity", "swords-2": "confusion", "swords-3": "end", "swords-4": "surrender",
  "swords-5": "conflict", "swords-6": "surrender", "swords-7": "isolation", "swords-8": "confusion",
  "swords-9": "confusion", "swords-10": "end", "swords-11": "clarity", "swords-12": "conflict",
  "swords-13": "clarity", "swords-14": "power",
  "pentacles-1": "begin", "pentacles-2": "instability", "pentacles-3": "growth", "pentacles-4": "instability",
  "pentacles-5": "isolation", "pentacles-6": "connection", "pentacles-7": "growth", "pentacles-8": "growth",
  "pentacles-9": "resource", "pentacles-10": "resource", "pentacles-11": "begin", "pentacles-12": "growth",
  "pentacles-13": "resource", "pentacles-14": "resource",
};

// 組成完整的 78 張牌陣列
const TAROT_DECK = [];

MAJOR_ARCANA.forEach((card) => {
  const id = `major-${card.num}`;
  TAROT_DECK.push({
    id,
    arcana: "major",
    name: card.name,
    subtitle: "大阿爾克那",
    img: `assets/cards/${card.img}`,
    keywords: { up: card.up, rev: card.rev },
    text: { up: card.upText, rev: card.revText },
    theme: CARD_THEMES[id],
  });
});

// 小阿爾克那圖片檔名的前綴（與 suitKey 不同，來源檔案用的是縮寫 "pents"）
const SUIT_FILE_PREFIX = { wands: "wands", cups: "cups", swords: "swords", pentacles: "pents" };

Object.keys(MINOR_ARCANA).forEach((suitKey) => {
  const suit = SUITS[suitKey];
  MINOR_ARCANA[suitKey].forEach((card) => {
    const id = `${suitKey}-${card.rank}`;
    TAROT_DECK.push({
      id,
      arcana: "minor",
      suit: suitKey,
      element: suit.element,
      name: `${suit.name}${RANK_LABELS[card.rank]}`,
      subtitle: `小阿爾克那・${suit.name}`,
      theme: CARD_THEMES[id],
      img: `assets/cards/${SUIT_FILE_PREFIX[suitKey]}${String(card.rank).padStart(2, "0")}.jpg`,
      keywords: { up: card.up, rev: card.rev },
      text: { up: card.upText, rev: card.revText },
    });
  });
});

// 抽卡牌陣設定
const SPREADS = [
  {
    id: "single",
    icon: "🔮",
    name: "每日一牌",
    desc: "抽一張牌，作為今天的內在指引。",
    positions: [{ key: "guide", label: "今日指引" }],
  },
  {
    id: "timeline3",
    icon: "⏳",
    name: "過去・現在・未來",
    desc: "從時間之流中，看清事件的來龍去脈。",
    positions: [
      { key: "past", label: "過去" },
      { key: "present", label: "現在" },
      { key: "future", label: "未來" },
    ],
  },
  {
    id: "mindbody3",
    icon: "🌙",
    name: "身・心・靈",
    desc: "從三個層次，探索你目前的整體狀態。",
    positions: [
      { key: "body", label: "身" },
      { key: "mind", label: "心" },
      { key: "spirit", label: "靈" },
    ],
  },
  {
    id: "relationship3",
    icon: "💞",
    name: "關係牌陣",
    desc: "探索你、對方，以及這段關係的樣貌。",
    positions: [
      { key: "you", label: "你的心" },
      { key: "other", label: "對方的心" },
      { key: "bond", label: "關係走向" },
    ],
  },
  {
    id: "star5",
    icon: "⭐",
    name: "五芒星牌陣",
    desc: "深入剖析現況、助力、阻礙、建議與可能結果。",
    positions: [
      { key: "situation", label: "現況" },
      { key: "help", label: "助力" },
      { key: "obstacle", label: "阻礙" },
      { key: "advice", label: "建議" },
      { key: "outcome", label: "可能結果" },
    ],
  },
];
